include = ["*.toml", ".cargo/*.toml", ".config/*.toml", "crates/**/*.toml", "xtask/**/*.toml"]
exclude = ["**/target/**", "reports/**", "**/.storage-scout-*/**"]

[formatting]
align_entries = false
column_width = 100
reorder_keys = false
